import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Spline from "@splinetool/react-spline";
import { useRef } from "react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>enzym.vfx</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <header className="flex items-center justify-end pr-5">
        <button>Home</button>
        <button>About</button>
        <button>Work</button>
        <button>Contact</button>
      </header>
      <main className="main flex items-start justify-center">
        <Spline scene="https://prod.spline.design/PSOHRGJ0t7vihQtp/scene.splinecode" />
      </main>
    </>
  );
};

export default Home;
